name: API Test Automation

on:
  push:
    branches:
      - main

jobs:
  api-test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pytest requests pytest-html jsonschema boto3

      - name: Run API Tests
        run: pytest